rules = [
  {"permit": "allow", "username": "public", "action": "subscribe", "topics": ["#"]},
  {"permit": "allow", "username": "#", "action": "subscribe", "topics": ["owntracks/#"]},
  {"permit": "allow", "username": "#", "action": "publish", "topics": ["owntracks/${username}/#"]},
  {"permit": "deny"}
]
